### ISSUE TITLE
Use same release version on GitHub and PyPI

### ISSUE THREAD

**Issue by davidak** [greenbone/gvm-tools#135]
### Expected behavior

GitHub, PyPI: 2.0.0b1

### Current behavior

GitHub: [v2.0.0.beta1](https://github.com/greenbone/gvm-tools/releases/tag/v2.0.0.beta1)
PyPI: [2.0.0b1](https://pypi.org/project/gvm-tools/2.0.0b1/)

**Comment by bjoernricks** [comment]
I am not a fan of the python pep440 version scheme. It looks a bit strange and 2.0.0b1 is actually the [normalized](https://pypi.org/project/packaging/) 2.0.0.beta1. We should discuss the versioning schema an implement it in https://github.com/greenbone/python-gvm/blob/master/gvm/utils.py#L20

@wiegandm what's your opinion about the versions?

**Comment by wiegandm** [comment]
> @wiegandm what's your opinion about the versions?

I ultimately would rather like to go towards [Semantic Versioning](https://semver.org/), but I guess we need to find a compromise with PEP440 and PyPIs normalization for the time being.

That being said, I would consider a solution along the lines of greenbone/python-gvm#70 as acceptable.

**Comment by bjoernricks** [comment]
I am still not confident with the solution in https://github.com/greenbone/python-gvm/pull/70 

* SemVer uses a `<major>.<minor>.<patch>-<pre-release>.<pre-release-version>` e.g. 1.2.3-beta.1 scheme.
* PEP440 uses `<major>.<minor>.<patch><shortend-pre-release><pre-release-version>` e.g. 1.2.3b1 scheme
* https://github.com/greenbone/python-gvm/pull/70 introduces `<major>.<minor>.<patch><pre-release><pre-release-version>` e.g. 1.2.3beta1
* My personal preference would be `<major>.<minor>.<patch>.<pre-release><pre-release-version>` e.g. 1.2.3.beta1

Because all of our git tags have a v prefix I would still keep it. Thus the tag would be v<version>.

I am still not convinced that it will be a problem for the users to distinct between git tags, version displayed with `--version` switch and pypi versions. So I am bit left on this topic currently but I really need a solution until wednesday because I am planning the next release.

**Comment by bjoernricks** [comment]
Additionally gsa, openvas-scanner, gvmd, gvm-libs used a `<major>.<minor>+<pre-release><pre-release-version>` e.g. 1.2+beta1 schema

**Comment by bjoernricks** [comment]
We have decided to use the  `<major>.<minor>.<patch>.<pre-release><pre-release-version>` e.g. 1.2.3.beta1 schema for python software.
